from __future__ import annotations

COUNTRY_TO_REGION = {
    "Africa_Other": "Africa",
    "Algerian": "Africa",
    "American": "Americas",
    "Americas_Other": "Americas",
    "Bahraini": "Middle_East",
    "Bangladeshi": "South_Asia",
    "Brazilian": "Americas",
    "British": "UK",
    "Canadian": "Americas",
    "Central_Asia_Other": "Central_Asia",
    "Chinese": "East_Asia",
    "East_Asia_Other": "East_Asia",
    "Egyptian": "Africa",
    "Emirati": "Middle_East",
    "Europe_Other": "Europe",
    "French": "Europe",
    "Hong Kong Chinese": "East_Asia",
    "Indian": "South_Asia",
    "Indonesian": "East_Asia",
    "Iranian": "Middle_East",
    "Iraqi": "Middle_East",
    "Irish": "Europe",
    "Italian": "Europe",
    "Japanese": "East_Asia",
    "Jordanian": "Middle_East",
    "Kazakhstani": "Central_Asia",
    "Kenyan": "Africa",
    "Korean": "East_Asia",
    "Kuwaiti": "Middle_East",
    "Lebanese": "Middle_East",
    "Libyan": "Africa",
    "Malaysian": "East_Asia",
    "Mexican": "Americas",
    "Middle_East_Other": "Middle_East",
    "Moroccan": "Africa",
    "Myanmarian": "East_Asia",
    "Nepalese": "South_Asia",
    "Nigerian": "Africa",
    "Oceania_Other": "Oceania",
    "Omani": "Middle_East",
    "Other": "Other",
    "Pakistani": "South_Asia",
    "Peruvian": "Americas",
    "Portuguese": "Europe",
    "Qatari": "Middle_East",
    "Russian": "Europe",
    "Saudi": "Middle_East",
    "Singaporean": "East_Asia",
    "South African": "Africa",
    "South_Asia_Other": "South_Asia",
    "Spanish": "Europe",
    "Sri Lankan": "South_Asia",
    "Sudanese": "Africa",
    "Syrian": "Middle_East",
    "Taiwanese": "East_Asia",
    "Thai": "East_Asia",
    "Turkish": "Europe",
    "UK_Other": "UK",
    "Ugandan": "Africa",
    "Ukrainian": "Europe",
    "Vietnamese": "East_Asia",
    "Zimbabwean": "Africa",
}
